version: '3.8'
services:
  api:
    build: .
    env_file:
      - .env
  postgres:
    image: postgres:10.3
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
